backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "comics"
    label: "Comics"
    folder: "comics"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Chapters", name: "chapters", widget: "list"}
